//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkCred.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ParkCred.Droid.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Features.
        /// </summary>
        internal static string ApplicationFeatures {
            get {
                return ResourceManager.GetString("ApplicationFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParkCred.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic parking.
        /// </summary>
        internal static string AutomaticParking {
            get {
                return ResourceManager.GetString("AutomaticParking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order a telematics device and get all the possibilities of automatic parking. It will no longer be necessary to regularly enter the application to start and end the parking session. Be engaged in really important affairs, and parking your car provide an opportunity to do business with us. The cost of the device and its installation is only 3,500 rubles. All the rest of the payment will be made solely in account of parking sessions. We do not charge for our automatic parking services..
        /// </summary>
        internal static string AutoParkingDescription {
            get {
                return ResourceManager.GetString("AutoParkingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic parking will allow you not to worry about that you forgot to park. When in the parking zone, the system will automatically park your car. To activate automatic parking, the installation of a telematics device is required..
        /// </summary>
        internal static string AutoParkingFunctionDescription {
            get {
                return ResourceManager.GetString("AutoParkingFunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic parking is activated. It will allow you not to worry about that you forgot to park. When in the parking zone, the system will automatically park your car..
        /// </summary>
        internal static string AutoParkingModeMessage {
            get {
                return ResourceManager.GetString("AutoParkingModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order to install the device is accepted. Wait for the call of a specialist..
        /// </summary>
        internal static string AutoParkingOrderAccepted {
            get {
                return ResourceManager.GetString("AutoParkingOrderAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advantages of CASCO.
        /// </summary>
        internal static string BenefitsTitle {
            get {
                return ResourceManager.GetString("BenefitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus system.
        /// </summary>
        internal static string BonusSystem {
            get {
                return ResourceManager.GetString("BonusSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying the CASCO policy you get the device for free.
        /// </summary>
        internal static string BuyPoliceTitle {
            get {
                return ResourceManager.GetString("BuyPoliceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel session.
        /// </summary>
        internal static string CancelSession {
            get {
                return ResourceManager.GetString("CancelSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car mark.
        /// </summary>
        internal static string CarMark {
            get {
                return ResourceManager.GetString("CarMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car model.
        /// </summary>
        internal static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car registration number.
        /// </summary>
        internal static string CarRegistrationNumber {
            get {
                return ResourceManager.GetString("CarRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of issue.
        /// </summary>
        internal static string CarYear {
            get {
                return ResourceManager.GetString("CarYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeZone.
        /// </summary>
        internal static string ChangeZone {
            get {
                return ResourceManager.GetString("ChangeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to change the zone?.
        /// </summary>
        internal static string ChangeZoneConfirmMessage {
            get {
                return ResourceManager.GetString("ChangeZoneConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current location.
        /// </summary>
        internal static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session.
        /// </summary>
        internal static string CurrentSession {
            get {
                return ResourceManager.GetString("CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To declare an insurance event and monitor the status of settlement of current insurance cases.
        /// </summary>
        internal static string DeclareInsuranceEvent {
            get {
                return ResourceManager.GetString("DeclareInsuranceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of the device with installation.
        /// </summary>
        internal static string DeviceCost {
            get {
                return ResourceManager.GetString("DeviceCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed discounts for prolongation.
        /// </summary>
        internal static string Discounts {
            get {
                return ResourceManager.GetString("Discounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the app from Google Play and start earning today!.
        /// </summary>
        internal static string DownloadAppTitle {
            get {
                return ResourceManager.GetString("DownloadAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time of the session end.
        /// </summary>
        internal static string DTOfSessionEnd {
            get {
                return ResourceManager.GetString("DTOfSessionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time of the session start.
        /// </summary>
        internal static string DTOfSessionStart {
            get {
                return ResourceManager.GetString("DTOfSessionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn bonus points for good driving and recommending us to your friends.
        /// </summary>
        internal static string EarnBonusPoints {
            get {
                return ResourceManager.GetString("EarnBonusPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable GPS!.
        /// </summary>
        internal static string EnableGPS {
            get {
                return ResourceManager.GetString("EnableGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End session.
        /// </summary>
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the location of your car on the map.
        /// </summary>
        internal static string FindCar {
            get {
                return ResourceManager.GetString("FindCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish and schedule.
        /// </summary>
        internal static string FinishAndSchedule {
            get {
                return ResourceManager.GetString("FinishAndSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free first.
        /// </summary>
        internal static string FirstTimeFreeTitle {
            get {
                return ResourceManager.GetString("FirstTimeFreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get free.
        /// </summary>
        internal static string GetFree {
            get {
                return ResourceManager.GetString("GetFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install Google Play Services for correct application.
        /// </summary>
        internal static string GooglePlayServicesNotInstalledMessage {
            get {
                return ResourceManager.GetString("GooglePlayServicesNotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help on the road.
        /// </summary>
        internal static string HelpOnRoad {
            get {
                return ResourceManager.GetString("HelpOnRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for insurance is accepted. Wait for the call of a specialist..
        /// </summary>
        internal static string InsuranceAccepted {
            get {
                return ResourceManager.GetString("InsuranceAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay every quarter less and less if you are a good driver.
        /// </summary>
        internal static string LessCost {
            get {
                return ResourceManager.GetString("LessCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scheduled parking session.
        /// </summary>
        internal static string NoScheduledParkingSession {
            get {
                return ResourceManager.GetString("NoScheduledParkingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order installation.
        /// </summary>
        internal static string OrderInstallation {
            get {
                return ResourceManager.GetString("OrderInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking area number.
        /// </summary>
        internal static string ParkingAreaNumber {
            get {
                return ResourceManager.GetString("ParkingAreaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking places.
        /// </summary>
        internal static string ParkingPlaces {
            get {
                return ResourceManager.GetString("ParkingPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start time of the parking session can not be earlier than the current time..
        /// </summary>
        internal static string ParkingSessionTimeMinusError {
            get {
                return ResourceManager.GetString("ParkingSessionTimeMinusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking status.
        /// </summary>
        internal static string ParkingStatus {
            get {
                return ResourceManager.GetString("ParkingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned session.
        /// </summary>
        internal static string PlannedSession {
            get {
                return ResourceManager.GetString("PlannedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly policy.
        /// </summary>
        internal static string QuarterlyPolicy {
            get {
                return ResourceManager.GetString("QuarterlyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replenish.
        /// </summary>
        internal static string Replenish {
            get {
                return ResourceManager.GetString("Replenish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rub..
        /// </summary>
        internal static string Rub {
            get {
                return ResourceManager.GetString("Rub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a parking session.
        /// </summary>
        internal static string ScheduleParkingSession {
            get {
                return ResourceManager.GetString("ScheduleParkingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At any time, see the main terms of your CASCO policy.
        /// </summary>
        internal static string SeeMainTerms {
            get {
                return ResourceManager.GetString("SeeMainTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your rating and improve the quality of your driving.
        /// </summary>
        internal static string SeeYourRating {
            get {
                return ResourceManager.GetString("SeeYourRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        internal static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified settlement (without a visit to the office).
        /// </summary>
        internal static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for parking session.
        /// </summary>
        internal static string WaitingForParkingSession {
            get {
                return ResourceManager.GetString("WaitingForParkingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
